# Generated by Django 5.2.1 on 2025-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoría',
            name='Nombre_C',
        ),
        migrations.AddField(
            model_name='categoría',
            name='nombre_c',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
