# Generated by Django 5.2.1 on 2025-05-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_categoría_nombre_c_categoría_nombre_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default=1, max_length=39),
            preserve_default=False,
        ),
    ]
