# Generated by Django 5.2.1 on 2025-05-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
    ]
