# Generated by Django 5.2.1 on 2025-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_usuario_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoría',
            name='descripcion_c',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
        migrations.AddField(
            model_name='categoría',
            name='imagen_c',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
