# Generated by Django 5.2.1 on 2025-06-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_categoría_descripcion_c_categoría_imagen_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='descripción_Servicio',
            field=models.TextField(default='Sin descripción', max_length=250),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Imagen_U',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
