# Generated by Django 5.2.1 on 2025-06-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_servicios_descripción_servicio_usuario_imagen_u'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='descripción_Servicio',
            new_name='descripcion_Servicio',
        ),
    ]
