# Generated by Django 5.2.1 on 2025-06-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_descripción_servicio_servicios_descripcion_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='usuario_trabajador',
        ),
    ]
