# Generated by Django 5.2.1 on 2025-06-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_servicios_usuario_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='usuario_trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
