# Generated by Django 5.2.1 on 2025-06-17 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_servicios_usuario_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='Categoria_Servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoría'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='descripcion_larga',
            field=models.TextField(default='Sin descripción', max_length=250),
        ),
        migrations.AddField(
            model_name='servicios',
            name='imagen_servicio',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
