# Generated by Django 5.2.1 on 2025-06-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_solicitud'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoría',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Servicios_Categorías',
            new_name='Servicios_Categorias',
        ),
    ]
