# Generated by Django 5.2.1 on 2025-06-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_categoría_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categoría',
        ),
        migrations.RenameModel(
            old_name='Servicios_Categorias',
            new_name='Servicios_Categorías',
        ),
    ]
